export const SirvicesInfo =[
    {
        id: 1,
        link: '/',
        img: '/images/ser1.svg',
        plan: 'Starter Pack',
        cost: '$99.99',
        length: 'per month',
        feature_0: '$100 New Users',
        feature_1: '$10,000 Budget',
        feature_2: 'Retargeting analytics',
        button: 'Choose Plan',
    },

    {
        id: 2,
        link: '/',
        img: '/images/ser2.svg',
        plan: 'Gold Rush',
        cost: '$299.99',
        length: 'per month',
        feature_0: '$100 New Users',
        feature_1: '$50,000 Budget',
        feature_2: 'Lead Gen Analytics',
        button: 'Choose Plan',
    },

    {
        id: 3,
        link: '/',
        img: '/images/ser3.svg',
        plan: 'Diamond Kings',
        cost: '$999.99',
        length: 'per month',
        feature_0: 'Unlimited Users',
        feature_1: 'Unlimited Budget',
        feature_2: '24/7 Support',
        button: 'Choose Plan',
    },
]